In [1]:
%matplotlib inline
import cv2
import numpy
import matplotlib.pyplot as plot
from PIL import ImageGrab

In [5]:
cap = cv2.VideoCapture('http://127.0.0.1:8080/live')

In [6]:
ret, frame = cap.read()


In [7]:
print ret

True


In [8]:
print frame

[[[142 135 146]
  [144 137 148]
  [146 139 150]
  ..., 
  [173 174 231]
  [139 139 194]
  [129 129 184]]

 [[144 137 148]
  [145 138 149]
  [147 140 151]
  ..., 
  [171 172 229]
  [139 139 194]
  [129 129 184]]

 [[146 139 150]
  [147 140 151]
  [149 142 153]
  ..., 
  [169 172 229]
  [139 139 194]
  [130 130 185]]

 ..., 
 [[  9  56  58]
  [ 11  58  60]
  [ 15  62  64]
  ..., 
  [ 48  75  71]
  [ 48  75  71]
  [ 48  75  71]]

 [[  9  56  58]
  [ 11  58  60]
  [ 15  62  64]
  ..., 
  [122 149 145]
  [122 149 145]
  [122 149 145]]

 [[  9  56  58]
  [ 11  58  60]
  [ 15  62  64]
  ..., 
  [ 15  42  38]
  [ 15  42  38]
  [ 15  42  38]]]


In [9]:
# show a frame
cv2.imshow("capture", frame)

In [1]:
import time

In [3]:
x = time.time()

In [4]:
time.time()-x

6.551000118255615